const products = [
    {
        id: 1,
        img: "/images/shop/plants/1.jpg",
        name: "bamboo palm",
        price: "1,500",
        categories: ["all plants", "indoor plants", "tall plants", "pet-friendly"],
      },
      {
        id: 2,
        img: "/images/shop/plants/2.jpg",
        name: "baston fern",
        price: "500",
        categories: ["all plants", "indoor plants", "table-top and shelf plants", "medium plants", "pet-friendly"],
      },
      {
        id: 3,
        img: "/images/shop/plants/3.jpg",
        name: "breath easy bundle",
        price: "650",
        categories: ["all plants", "indoor plants", "specials", "table-top and shelf plants", "sets"],
      },
      {
        id: 4,
        img: "/images/shop/plants/4.jpg",
        name: "brighten your day bundle",
        price: "750",
        categories: ["all plants", "indoor plants", "specials", "table-top and shelf plants", "sets"],
      },
      {
        id: 5,
        img: "/images/shop/plants/5.jpg",
        name: "butterfly palm",
        price: "1,200",
        categories: ["all plants", "indoor plants", "tall plants", "pet-friendly"],
      },
      {
        id: 6,
        img: "/images/shop/plants/19.jpg",
        name: "cactus",
        price: "800",
        categories: ["all plants", "medium plants"],
      },
      {
        id: 7,
        img: "/images/shop/plants/6.jpg",
        name: "dracaena anita",
        price: "1,200",
        categories: ["all plants", "indoor plants", "tall plants"],
      },
      {
        id: 8,
        img: "/images/shop/plants/7.jpg",
        name: "dwarf sansevieria | snake plant",
        price: "300",
        categories: ["all plants", "indoor plants", "specials", "table-top and shelf plants"],
      },
      {
        id: 9,
        img: "/images/shop/plants/20.jpg",
        name: "fiddle-leaf fig",
        price: "1,500",
        categories: ["all plants", "medium plants", "tall plants"],
      },
      {
        id: 10,
        img: "/images/shop/plants/8.jpg",
        name: "golden pothos",
        price: "300",
        categories: ["all plants", "indoor plants", "table-top and shelf plants"],
      },
      {
        id: 11,
        img: "/images/shop/plants/17.jpg",
        name: "heartleaf philodendron",
        price: "500",
        categories: ["all plants", "table-top and shelf plants"],
      },
      {
        id: 12,
        img: "/images/shop/plants/9.jpg",
        name: "heartleaf philodendron | special pot",
        price: "400",
        categories: ["all plants", "indoor plants", "specials", "table-top and shelf plants"],
      },
      {
        id: 13,
        img: "/images/shop/plants/25.jpg",
        name: "licuala grandis",
        price: "1,500",
        categories: ["all plants", "tall plants", "pet-friendly"],
      },
      {
        id: 14,
        img: "/images/shop/plants/21.jpg",
        name: "livistona",
        price: "1,200",
        categories: ["all plants", "indoor plants", "medium plants", "tall plants", "pet-friendly", "outdoor plants"],
      },
      {
        id: 15,
        img: "/images/shop/plants/26.jpg",
        name: "macArthur palm",
        price: "1,500",
        categories: ["all plants", "tall plants"],
      },
      {
        id: 16,
        img: "/images/shop/plants/11.jpg",
        name: "moonshine sansevieria | snake plant",
        price: "400",
        categories: ["all plants", "indoor plants", "specials", "table-top and shelf plants"],
      },
      {
        id: 17,
        img: "/images/shop/plants/12.jpg",
        name: "peace lily",
        price: "1,300",
        categories: ["all plants", "indoor plants", "medium plants"],
      },
      {
        id: 18,
        img: "/images/shop/plants/18.jpg",
        name: "peperomia obtusifolia",
        price: "500",
        categories: ["all plants", "table-top and shelf plants", "pet-friendly"],
      },
          {
        id: 19,
        img: "/images/shop/plants/22.jpg",
        name: "philodendron giganteum",
        price: "1,500",
        categories: ["all plants", "indoor plants", "medium plants"],
      },
      {
        id: 20,
        img: "/images/shop/plants/23.jpg",
        name: "philodendron selloum",
        price: "1,000",
        categories: ["all plants", "indoor plants", "medium plants"],
      },
      {
        id: 21,
        img: "/images/shop/plants/27.jpg",
        name: "podocarpus macrophyllus 'Maki'",
        price: "1,000",
        categories: ["all plants", "tall plants", "outdoor plants"],
      },
      {
        id: 22,
        img: "/images/shop/plants/13.jpg",
        name: "potted plants collection",
        price: "500",
        categories: ["all plants", "indoor plants", "specials", "table-top and shelf plants", "gifts"],
      },
      {
        id: 23,
        img: "/images/shop/plants/24.jpg",
        name: "rhapis excelsa",
        price: "1,000",
        categories: ["all plants", "indoor plants", "medium plants", "pet-friendly"],
      },
      {
        id: 24,
        img: "/images/shop/plants/14.jpg",
        name: "snake plant bundle",
        price: "650",
        categories: ["all plants", "indoor plants", "specials", "table-top and shelf plants", "sets"],
      },
      {
        id: 25,
        img: "/images/shop/plants/15.jpg",
        name: "two hearts bundle",
        price: "750",
        categories: ["all plants", "indoor plants", "specials", "table-top and shelf plants", "sets"],
      },
      {
        id: 26,
        img: "/images/shop/plants/28.jpg",
        name: "various hebrs",
        price: "450",
        categories: ["all plants", "herbs"],
      }
  ]